---
- name: Check for available updates on Ubuntu
  hosts: all
  become: yes  # Ensure commands are run as root
  tasks:
    - name: Check for available upgrades
      command: apt list --upgradable
      register: upgradable_packages
      changed_when: false  # Don't mark the task as changed

    - name: Display available upgrades
      debug:
        msg: "The following packages can be upgraded: {{ upgradable_packages.stdout }}"
      when: upgradable_packages.stdout != ""
