---
- name: Check installed packages and updates
  hosts: all
  become: yes  # Ensure commands are run as root
  tasks:
    - name: Check history of installed packages
      command: grep "install " /var/log/dpkg.log
      register: installed_packages
      changed_when: false  # We are just checking the logs, so no changes

    - name: Display installed packages
      debug:
        msg: "Installed packages: {{ installed_packages.stdout_lines }}"
      when: installed_packages.stdout != ""
