---
- name: Check OS version on all hosts
  hosts: all
  gather_facts: yes  # This collects system information
  tasks:
    - name: Display the OS version
      debug:
        msg: "The OS is {{ ansible_distribution }} version {{ ansible_distribution_version }}"
