---
- name: Check and list packages needing updates
  hosts: all
  become: yes  # Ensure commands are run as root
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
        cache_valid_time: 3600  # Cache valid for 1 hour

    - name: Get a list of upgradable packages
      command: apt list --upgradable
      register: upgradable_packages
      changed_when: false

    - name: Display a well-organized list of upgradable packages
      debug:
        msg: |
          {% if upgradable_packages.stdout != "" %}
            #### Packages Needing Updates ####
            The following packages have updates available:
            
            {{ upgradable_packages.stdout | regex_findall('^[^/]+') | sort | join('\n') }}
            
            ##################################
          {% else %}
            #### No Packages Need Updates ####
            Your system is up to date.
            ##################################
          {% endif %}
